"""empty message

Revision ID: 1e579cb5b182
Revises: 73e77cf55943
Create Date: 2023-01-06 11:30:56.126209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e579cb5b182'
down_revision = '73e77cf55943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nombre', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nombre')
    # ### end Alembic commands ###
